# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-18 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0002_auto_20180218_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='emil',
            new_name='email',
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=django.utils.timezone.now, verbose_name=1000),
            preserve_default=False,
        ),
    ]
