# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-24 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0002_auto_20180224_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]